//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinanceFuturesViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://fapi.binance.com")]
        public string FuturesRestBaseUrl {
            get {
                return ((string)(this["FuturesRestBaseUrl"]));
            }
            set {
                this["FuturesRestBaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wss://fstream.binance.com/market/ws")]
        public string FuturesWebSocketBaseUrl {
            get {
                return ((string)(this["FuturesWebSocketBaseUrl"]));
            }
            set {
                this["FuturesWebSocketBaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/fapi/v1/exchangeInfo")]
        public string ExchangeInfoEndpoint {
            get {
                return ((string)(this["ExchangeInfoEndpoint"]));
            }
            set {
                this["ExchangeInfoEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/fapi/v1/klines")]
        public string KlinesEndpoint {
            get {
                return ((string)(this["KlinesEndpoint"]));
            }
            set {
                this["KlinesEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BTCUSDT")]
        public string DefaultSymbol {
            get {
                return ((string)(this["DefaultSymbol"]));
            }
            set {
                this["DefaultSymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1h")]
        public string DefaultInterval {
            get {
                return ((string)(this["DefaultInterval"]));
            }
            set {
                this["DefaultInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public int DefaultCandlesLimit {
            get {
                return ((int)(this["DefaultCandlesLimit"]));
            }
            set {
                this["DefaultCandlesLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int DefaultComparisonWindow {
            get {
                return ((int)(this["DefaultComparisonWindow"]));
            }
            set {
                this["DefaultComparisonWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal DefaultDistanceThreshold {
            get {
                return ((decimal)(this["DefaultDistanceThreshold"]));
            }
            set {
                this["DefaultDistanceThreshold"] = value;
            }
        }
    }
}
